apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-end
spec:
  replicas: 3
  selector:
    matchLabels:
      app: back-end
  template:
    metadata:
      name: back-end-pod
      labels:
        app: back-end
    spec:
      containers:
      - name: fastapi-server
        image: 165304734991.dkr.ecr.ap-northeast-1.amazonaws.com/cloudcrew-be:test01
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_USER
        - name: DB_PWD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PWD
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_NAME
        - name: COL_NAME
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: COL_NAME
